server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/expense_tracker
spring.datasource.username=expense_user
spring.datasource.password=expense_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true